### ISSUE TITLE
Etiquetas de encabezado

### ISSUE THREAD

**Issue by DanBaDo** [ManuelCasadoP/Curriculum#1]
https://github.com/ManuelCasadoP/Curriculum/blob/7f10826455755d71aa1cdcfc55d028d21a3423ea/src/index.html#L18-L24

Las etiquetas de encabezado `h1`, `h2`, `h3`... deben de emplearse únicamente para títulos de secciones. Si deseamos dar más peso a determinados contenidos tendremos otros recursos que nos permitirán modificar el aspecto del texto.

**Comment by ManuelCasadoP** [comment]
Entendido. A ver si lo recuerdo la siguiente vez.
